server:
  port: 8085
  context-path: /${spring.application.name}
#默认使用配置
spring:
  profiles:
    active: dev
  application:
    name: java/fabric


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    plugins:
      plugin:
        interceptor: com.example.demo.common.PageInterceptor


---
#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver